### ISSUE TITLE
Official conda package?

### ISSUE THREAD

**Issue by schlepuetz** [PandABlocks/PandABlocks-client#32]
I found pandablocks on conda-forge (https://anaconda.org/conda-forge/pandablocks). Is this an official release from the project? If yes, it would be nice to mention that in the installation instructions (https://pandablocks.github.io/PandABlocks-client/master/tutorials/installation.html).
Also, I've noticed that since the last release (0.2.1, Dec. 2020), a substantial amount of development has happened. Would it be possible to make this available for easy installation via pip and conda through a new release?

Many thanks for the great work! We are only just getting started with our new PandABox, but it's already making a big impact on our measurements. And that impact will be amplified even more once we get our python environments sorted out!

**Comment by AlexanderWells-diamond** [comment]
As far as I'm aware that is an unofficial release. We don't publish anything to conda-forge, just PyPi. 

I'll leave the release question to someone else, probably @thomascobb

**Comment by schlepuetz** [comment]
@AlexanderWells-diamond : Many thanks for the quick reply. I will use the PyPi release then for the moment.

**Comment by beenje** [comment]
Hi!
I'm the maintainer of the conda-forge package. Anyone can propose a package on conda-forge. You don't need to have a link with the upstream project.

Packages are accepted after a review process in the [staged-recipes](https://github.com/conda-forge/staged-recipes) repo.
Sources shall be from an official source. For Python, it's usually the git repo or pypi.

So I'd say it's quite safe to trust the packages from `conda-forge` (at least as any package you download from the internet). You can check the `pandablocks` recipe here: https://github.com/conda-forge/pandablocks-feedstock/blob/main/recipe/meta.yaml

**Comment by AlexanderWells-diamond** [comment]
I'm afraid I don't see the conda-forge package as being a good idea. From the looks of that recipie, there's quite a lot of parts that could easily become misaligned:

- The build - entry_points section specifies the `cli` file. There's no guarantee that won't change
- It looks like the recipe lists requirements, which duplicates what already appears in our Pipfile / setup.cfg 
- Most of the strings in the "about" section could change at any time

I'll admit I have no knowledge of conda-forge at all, but I fail to see how duplicating the package's location with a chance for a lot of bits and pieces to become misaligned is useful
