### ISSUE TITLE
Add PandA bob file server

### ISSUE THREAD

**Issue by coretl** [PandABlocks/PandABlocks-client#39]
First make an aiohttp project that serves `/<filename>.bob` returning "Hello <filename>" as the text

Then starting from https://github.com/PandABlocks/PandABlocks-client/tree/pvi_for_pythonsoftioc

- Integrate the aiohttp server into the startup of the ioc: https://github.com/PandABlocks/PandABlocks-client/blob/afe304fd9ad5b8f25ca4c7f7bd10319f164221b2/pandablocks/ioc/ioc.py#L109
- Make this code put the files in an internal dict: https://github.com/PandABlocks/PandABlocks-client/blob/pvi_for_pythonsoftioc/pandablocks/ioc/_pvi.py#L186-L198
- Serve those files on request from aiohttp

**Comment by tizayi** [comment]
172.23.252.201

**Comment by coretl** [comment]
bob file exporting has moved to PandABlocks-ioc
