### ISSUE TITLE
Add PVA extensions to serve Tables and Combo

### ISSUE THREAD

**Issue by coretl** [PandABlocks/PandABlocks-client#42]
To use what we have in https://github.com/coretl/nt_table_test

**Comment by coretl** [comment]
@RAYemelyanova

**Comment by coretl** [comment]
- [ ] Try running the phoebus screen with `pva://` prefix to PV and check it works
- [ ] Add `info(Q:form, "String")` to the LABEL fields of the PandA records a bit like https://github.com/coretl/nt_table_test/blob/master/nt_table_ioc.py#L21-L31
- [ ] Extend https://github.com/epics-containers/pvi/blob/master/src/pvi/device.py#L114 to have `choices` like `BitField` has `labels`, then specify them in the bit_mux and pos_mux creation code somewhere after https://github.com/PandABlocks/PandABlocks-client/blob/pvi_for_pythonsoftioc/pandablocks/ioc/ioc.py#L1023
- [ ] Add this widget for the `table` type: https://github.com/epics-containers/pvi/blob/master/src/pvi/device.py#L133 after https://github.com/PandABlocks/PandABlocks-client/blob/pvi_for_pythonsoftioc/pandablocks/ioc/ioc.py#L1103 using https://github.com/coretl/nt_table_test/blob/master/nt_table_ioc.py#L45-L92

**Comment by RAYemelyanova** [comment]
Note:

To get phoebus to display the Pandablocks IOC information, do the following:

1. go to pandablocks-client repository, having checked out the bobfile-server branch (soon should be merged into master).
2. activate venv and run `$ pandablocks softioc 172.23.252.201 SOME-PREFIX`
3. Go to scratch/phoebus/phoebus-4.6.10-SNAPSHOT and run phoebus like so, `./phoebus.sh -resource "http://localhost:8080/TTLOUT1.bob" ` Or any other bob file now available on localhost:8080
4. Screen should open.

**Comment by RAYemelyanova** [comment]
Currently blocked as, although I can add the information so pv access can see the info, phoebus doesn't seem to recognize it.

Current task is to talk to Joe Shannon about making a local dev build of Phoebus and modifying the Vtypes to understand the information via pv access.

**Comment by coretl** [comment]
The third item is captured in https://github.com/epics-containers/pvi/issues/25

**Comment by coretl** [comment]
Going to make a fake PandA for @RAYemelyanova

**Comment by coretl** [comment]
Repo is here: https://github.com/coretl/pvi_qsrv_tags

**Comment by coretl** [comment]
https://github.com/bluesky/ophyd-epics-devices/tree/panda-ideas

**Comment by coretl** [comment]
https://github.com/bluesky/ophyd/pull/1096
