### ISSUE TITLE
Add helper function converts Sequencer Table Line into an integer

### ISSUE THREAD

**Issue by zhulincqu** [PandABlocks/PandABlocks-client#49]
When we use `PandABlocks-client`to update/append sequencer table lines, we have to convert each sequencer table line from __Name__ into __Bit Field__ according to the [sequencer table line composition](http://localhost:8008/fpga_docs//build/seq_doc.html).

We created a function to convert and hope it can be added to the upstream.

**Comment by AlexanderWells-diamond** [comment]
The document link you provided is to localhost. Is there an online version of this document?

I see you're in the process of creating a fork, so once you make a PR we can review it.

**Comment by zhulincqu** [comment]
Here is the online version: [Sequencer Table Line Composition](https://pandablocks.github.io/PandABlocks-FPGA/master/build/seq_doc.html#sequencer-table-line-composition) 

Where should I put it? it is just a helper function. Maybe a `utils.py`

**Comment by AlexanderWells-diamond** [comment]
Feel free to put it into a `utils.py`, and we can always review if there's a better place for it. It would be good to see the code before working out where to put it.
