### ISSUE TITLE
Write absolute timestamps to HDF file

### ISSUE THREAD

**Issue by coretl** [PandABlocks/PandABlocks-client#80]
Write the following to HDF file from the header:

| header item | description |
| --- | --- |
| arm_time |         System timestamp when ARM command was sent |
| start_time |       Timestamp of when PCAP became both armed and enabled |
| hw_time_offset_ns | Offset in ns from hardware timestamp to captured system time, only present when hardware time source is used. |

The last field requires https://github.com/PandABlocks/PandABlocks-server/pull/45, and this also makes the fields nanosecond precision

@dmgav I propose that we keep the timestamp arrays like `TS_START` relative, and add these as top level HDF attributes to the root of the HDF file as [ISO 8601 UTC format](https://en.wikipedia.org/wiki/ISO_8601) with nanosecond resolution, i.e. `YYYY-MM-DDTHH:mm:ss.sssssssssZ`. What do you reckon?

**Comment by coretl** [comment]
If you have time that would be great. A rough list of things I think would need doing:
- Adding `start_time`, etc. to `StartData` structure: https://github.com/PandABlocks/PandABlocks-client/blob/2ecafc480402e792afd0b7e84037ae3f9dbb3be9/src/pandablocks/responses.py#L253-L268
- Filling them in from the header: https://github.com/PandABlocks/PandABlocks-client/blob/2ecafc480402e792afd0b7e84037ae3f9dbb3be9/src/pandablocks/connections.py#L331-L337
- Writing them as attributes in the HDF writer: https://github.com/PandABlocks/PandABlocks-client/blob/2ecafc480402e792afd0b7e84037ae3f9dbb3be9/src/pandablocks/hdf.py#L110-L125
- Adding a test for it
- Adding it to the docs

**Comment by dmgav** [comment]
Yes, I will be involved in testing Panda timestamping anyway, so I can work on this issue in the process. You can assign this issue to me.

**Comment by danielballan** [comment]
Thanks for asking, @dmgav. I think we can work with this, I don't foresee any issues.

**Comment by abbiemery** [comment]
Closed with #81
